### ISSUE TITLE
URL no longer exists

### ISSUE THREAD

**Issue by Ch3ck** [EliteProgrammersClub/eliteprogrammersclub.cf#2]
It seems like this site is down.

**Comment by najela** [comment]
The URL works from here

![screenshot 2015-12-21 09 01 27](https://cloud.githubusercontent.com/assets/4196457/11926036/870d2172-a7c1-11e5-8efb-efe25e006c8b.png)

**Comment by Ch3ck** [comment]
Then @najela I should have been having a network issue. Could you please add the details to the mailing list on the Black Hackers details?
